services:
    datamaps-client-ts:
        container_name: datamaps-client-ts
        build:
            context: ../
            dockerfile: docker/node/Dockerfile
        user: "1000:1000"
        ports:
            - "3000:3000"
        volumes:
            - "../:/usr/src/app"
        command: "nodemon -L src/nodeserver.ts"
        networks:
            - datamaps-client-ts-network

    datamaps-client-ts-nginx:
        container_name: "datamaps-client-ts-front-nginx"
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ../dist:/var/dist
            - ./front-nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./front-nginx/conf.d/:/etc/nginx/conf.d
        networks:
            - datamaps-client-ts-network

networks:
    datamaps-client-ts-network:
        name: "datamaps-client-ts-network"
        driver: bridge
        enable_ipv6: true
        ipam:
            config:
                - subnet: fd00:2:1::/112
                  gateway: fd00:2:1::1
